#define LEFT_LED_COUNT 250
#define RIGHT_LED_COUNT 252
#define RGB_LED_COUNT (LEFT_LED_COUNT+RIGHT_LED_COUNT)
#define RGB_LED_BYTE_COUNT (RGB_LED_COUNT * 3)

const uint8_t nyan0[RGB_LED_BYTE_COUNT] = {0};